apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-postgres-class
provisioner: kubernetes.io/nfs  # NFS provisioner
parameters:
  server: {{ .Values.db.persistence.volumeClaimTemplate.spec.nfsServer }}  #  NFS server address
  path: /data/db        # The NFS path
