apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-save-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.filesave.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.filesave.persistence.size }}
