apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-nginx-class
  resources:
    requests:
      storage: {{ .Values.nginx.persistence.size }}