apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    
    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;
    
    events {
        worker_connections  1024;
    }
    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
    
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
    
        access_log  /var/log/nginx/access.log  main;
    
        sendfile        on;
        #tcp_nopush     on;
    
        keepalive_timeout  65;
    
        # Enable gzip if you want compression
        # gzip  on;
    
        # Include any other NGINX config files if necessary
        include /etc/nginx/conf.d/*.conf;
    
        server {
            listen 80;  # This listens on port 80 (HTTP)
            server_name issy.site;  # Default server for handling any requests
    
            # Serve static files (index.html)
            location / {
                root /usr/share/nginx/html;  # Path to your index.html (container filesystem)
                index index.html;  # Default file to serve
                try_files $uri $uri/ =404;  # Try to find requested files, otherwise show 404
            }
                           
            # Proxy requests to Flask backend API (Adjust the port as per your Flask app)
            location /friend/ {
                proxy_pass http://retrive-data-api-service:5003;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto https;
                proxy_redirect off;
                
            }
    
            location /add_event/ {
                proxy_pass http://add-event-api-service:5004;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_redirect off;
            }
    
            location /add_friend/ {
                proxy_pass http://addfriend-api-service:5005;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_redirect off;
            }
    
            # Error page handling (optional, you can define custom error pages)
            error_page  404 /404.html;
            location = /404.html {
                root /usr/share/nginx/html;
            }
    
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root /usr/share/nginx/html;
            }
        }
    }
    
    
