apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      restartPolicy: {{ .Values.db.restartPolicy }}
      containers:
        - name: db
          image: {{ .Values.db.image }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.db.postgresUser }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.postgresPassword }}
            - name: POSTGRES_DB
              value: {{ .Values.db.postgresDb }}
          ports:
            - containerPort: {{ .Values.db.port }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-db-pvc
        - name: init-sql
          configMap:
            name: init-sql-configmap
