apiVersion: apps/v1
kind: Deployment
metadata:
  name: addfriend-api-deployment
  namespace: {{ .Values.namespace }}
  annotations:
    argocd-image-updater.argoproj.io/image-list: "{{ .Values.addEvent.image }}:{{ .Values.addEvent.tag }}"
    argocd-image-updater.argoproj.io/my-app.update-strategy: semver
spec:
  replicas: {{ .Values.addFriend.replicaCount }}
  selector:
    matchLabels:
      app: addfriend-api
  template:
    metadata:
      labels:
        app: addfriend-api
    spec:
      restartPolicy: {{ .Values.addFriend.restartPolicy }}
      containers:
        - name: addfriend-api
          image: "{{ .Values.addFriend.image }}:{{ .Values.addEvent.tag }}"
          env:
            - name: FLASK_APP
              value: {{ .Values.addFriend.flaskApp }}
            - name: FLASK_ENV
              value: "development"
          ports:
            - containerPort: {{ .Values.addFriend.port }}


