apiVersion: v1
kind: Service
metadata:
  name: filesave-api-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: filesave-api
  ports:
    - protocol: TCP
      port: {{ .Values.filesave.port }}
      targetPort: {{ .Values.filesave.port }}
