apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-filesave-pv
  namespace: talker-dev
spec:
  capacity:
    storage: {{ .Values.filesave.persistence.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-file-save-class
  nfs:
    path: {{ .Values.filesave.persistence.volumeClaimTemplate.volumeMountPath }}
    server:  {{ .Values.filesave.persistence.volumeClaimTemplate.nfsServer }}  #  NFS server address
