apiVersion: batch/v1
kind: CronJob
metadata:
  name: git-sync-to-nfs
  namespace: {{ .Values.namespace }}
spec:
  schedule: "{{ .Values.git-sync-to-nfs.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: git-sync
              image: alpine:latest  # Small image with Git and rsync installed
              command:
                - /bin/sh
                - -c
                - |
                  apk update
                  apk add git
                  apk add git rsync
                  git clone "{{ .Values.git-sync-to-nfs.git }}" /tmp/repo
                  rsync -av --delete /tmp/repo/prod/nginxhtml /mnt/nfs/  # Sync to the NFS mount point
              volumeMounts:
                - name: nfs-volume
                  mountPath: /mnt/nfs  # Mount the NFS volume at /mnt/nfs in the container
          volumes:
            - name: nfs-volume
              persistentVolumeClaim:
                claimName: nginx-pvc  
          restartPolicy: OnFailure
