apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: talker-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/secure-backends: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: nginx-tls-secret
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
      - path: /add_friend/
        pathType: Prefix
        backend:
          service:
            name: addfriend-api-service
            port:
              number: 5005
      - path: /friend/
        pathType: Prefix
        backend:
          service:
            name: retrive-data-api-service
            port:
              number: 5003
      - path: /add_event/
        pathType: Prefix
        backend:
          service:
            name: add-event-api-service
            port:
              number: 5004
      - path: /file_save/
        pathType: Prefix
        backend:
          service:
            name: filesave-api-service
            port:
              number: 5004
