apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-postgres-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # NFS supports ReadWriteMany access mode
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-postgres-class
  nfs:
    path: /data/db  # The NFS directory for PostgreSQL
    server: {{ .Values.db.persistence.volumeClaimTemplate.spec.nfsServer }}  #  NFS server address