apiVersion: v1
kind: Service
metadata:
  name: add-event-api-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: add-event-api
  ports:
    - protocol: TCP
      port: {{ .Values.addEvent.port }}
      targetPort: {{ .Values.addEvent.port }}
