apiVersion: v1
kind: Service
metadata:
  name: retrive-data-api-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: retrive-data-api
  ports:
    - protocol: TCP
      port: {{ .Values.retriveData.port }}
      targetPort: {{ .Values.retriveData.port }}
