apiVersion: v1
kind: Service
metadata:
  name: addfriend-api-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: addfriend-api
  ports:
    - protocol: TCP
      port: {{ .Values.addFriend.port }}
      targetPort: {{ .Values.addFriend.port }}
