apiVersion: v1
kind: Service
metadata:
  name: summarize-api-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: summarize-api
  ports:
    - protocol: TCP
      port: {{ .Values.summarize.port }}
      targetPort: {{ .Values.summarize.port }}
