name: Flask API CI Pipeline

on:
  push:
    branches:
      - main  
    paths:
      - 'dev/api/add_event_api/**'
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  # Job for add_event_api
  test_add_event_api:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies for add_event_api
      - name: Install dependencies for add_event_api
        run: |
          python -m pip install --upgrade pip
          pip install -r dev/api/add_event_api/requirements.txt  

      # Example GitHub Actions step to run flake8
      - name: Run flake8 linter
        run: |
          pip install flake8
          flake8 --max-line-length=140 dev/api/add_event_api/add_event_api.py  

      # Run Flask API test for add_event_api (ensure the test script is present and correctly written)
      - name: Run Flask API Test for add_event_api
        run: |
          python -m unittest dev/api/add_event_api/test/test_add_event_api.py
