name: Flask API CI Pipeline

on:
  push:
    branches:
      - main  
    paths:
      - 'dev/api/**'
jobs:
  test_flask_api:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # List all your Flask API folders here
        api_folder:
          - dev/api/add_event_api
          - dev/api/another_flask_api  # Add more APIs if necessary

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ matrix.api_folder }}/requirements.txt  # Adjust path as needed

      # Run the Flask API test (or replace this with your test command)
      - name: Run Flask API Test
        run: |
          python ${{ matrix.api_folder }}/app.py  # Replace with your app/script name
