name: HTML Files CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'dev/htmlfile/**'
  workflow_dispatch:  # Allow manual triggering of the workflow
  
jobs:
  validate_html_files:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install HTML Linter
      - name: Install HTML Linter
        run: |
          sudo apt-get install -y htmlhint  # Example: You can replace with another linter if needed

      # Run HTML check (adjust the path to your HTML directory)
      - name: Check HTML files
        run: |
          htmlhint dev/htmlfiles/**/*.html  # Run linter on all .html files in the folder

      # If HTML check passes, copy files to deployment folder
      - name: Copy HTML files for deployment
        run: |
          cp dev/htmlfiles/*.html /path/to/deployment/folder/  # Adjust path to deployment folder

      # Commit and push the changes to GitHub (optional)
      - name: Commit HTML changes
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          git add .
          git commit -m "Update HTML files for deployment"
          git push
