name: HTML Files CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'dev/htmlfile/**'
  workflow_dispatch:  # Allow manual triggering of the workflow
  
jobs:
  validate_html_files:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install Node.js and npm
      - name: Install Node.js
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm  # Install Node.js and npm for the HTMLHint to work

      # Install HTML Linter (HTMLHint)
      - name: Install HTMLHint
        run: |
          sudo npm install -g htmlhint
      # Run HTML check (adjust the path to your HTML directory)
      - name: Check HTML files
        run: |
          htmlhint dev/htmlfile/**/*.html  # Run linter on all .html files in the folder

      # If HTML check passes, copy files to deployment folder
      - name: Copy HTML files for deployment
        run: |
          cp -r dev/htmlfile/*.html prod/nginxhtml/  

      # List the target directory after copying
      - name: List target directory after copy
        run: |
          echo "Listing files in prod/nginxhtml after copy:"
          ls -la prod/nginxhtml/
          
      # Commit the changes and push back to GitHub
      - name: Commit and push changes
        run: |
          git config --global user.name "Issyanofsky"
          git config --global user.email "ecyanofsky@gmail.com"
          git add prod/nginxhtml/*.html  # Add the copied files to the staging area
          git commit -m "Copied HTML files to prod/nginxhtml"  # Commit the changes
          git push origin main  # Push the changes to the main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
